name: dev

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main","dev" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 
                             
    env:
      Solution_Name: MauiForKimai.sln                         
              
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: "Run build"
      run: dotnet build src/MauiForKimai.App/MauiForKimai.App.csproj -f net7.0-windows10.0.19041.0
      
    - name: "Run tests"
      run: dotnet test src/MauiForKimai.Tests/MauiForKimai.Tests.csproj -f net7.0
      
     

