name: dev

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 
                             
    env:
      Solution_Name: MauiForKimai.sln                         
              
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: "Run build script"
      run: dotnet build src/MauiForKimai.App/MauiForKimai.csproj -f net7.0-windows10.0.19041.0
     

